package com.fiveexceptions.testaar

internal class Logic {
    fun addNumber(number1 : Int ,number2 : Int ) : Int{
        return (number1+number2)
    }
}